### ISSUE TITLE
 Ubacivanje robota u Webots

### ISSUE THREAD

**Issue by filiparag** [memristor/mep3#10]
## To do
- [ ] Probni robot
  - [x] Osnovni model (#8)
  - [x] Motori za točkove (#8)
  - [ ] Senzori udaljenosti
  - [x] Rotacioni enkoderi na točkovima
  - [x] Lidar
  - [ ] ...
- [x] Veliki robot
  - [ ] ...
- [ ] Mali robot
  - [ ] ...

**Comment by lukicdarkoo** [comment]
Mozemo odmah staviti:
- senzore udaljenosti
- enkodere na tockovima
- lidar
