### ISSUE TITLE
Bad rotation estimation with ArUco tags (z axis flipped)

### ISSUE THREAD

**Issue by VladimirVincan** [memristor/mep3#104]
Additional info about the problem can be found on this [link](https://github.com/opencv/opencv/issues/8813).
We need to find a way to tell the PnP algorithm that the _z_ axis is always faced up, in order to minimize the **rotation** error.
Also, it would be nice if we could tell the algorithm that the _z_ axis distance from the world frame (e.g. ArUco tag no. 42) is always 510 mm, in order to minimize the **translation** error. 

![rotacija-zajedno](https://user-images.githubusercontent.com/13640533/156471646-4bea9bf3-164b-4d86-883a-1eb5ee127c99.gif)

https://user-images.githubusercontent.com/13640533/156472534-c4f9f414-01c5-40c4-a420-b13713f983c8.mp4

**Comment by VladimirVincan** [comment]
Pogledati ovaj komentar i sledeći algoritam: [komentar](https://stackoverflow.com/questions/51709522/unstable-values-in-aruco-pose-estimation#comment90618214_51736875) [algoritam](https://docs.opencv.org/4.1.0/d9/d0c/group__calib3d.html#ga549c2075fac14829ff4a58bc931c033d)

**Comment by VladimirVincan** [comment]
Examples of wrong orientations ([normalized vector], degrees):
angle-axis: [-0.33265696  0.46720817  0.81918   ], 141.78825742681315

**Comment by angstrem98** [comment]
Šta misliš da ti kad detektujes aruco (dobiješ njegov frame) proveriš da li osa z gleda na gore i ako ne ručno primeniš dodatnu rotaciju na frame i onda objaviš? Malo primitivno rešenje, ali čini mi se dosta brže nego da se razvija algoritam dalje.
