### ISSUE TITLE
Lidar doesn't detect cylinders in Webots

### ISSUE THREAD

**Issue by VladimirVincan** [memristor/mep3#105]
commit: 2f84846dc0b9016992bafd63d834d4f59c72d9d8

The cylinders that hold the hat are added but they are not detected by the Lidar. The bounding object and physics have been added to the cylinders. Is there something else needed to be added to the cylinders in order for them to be detected or does the Lidar not publish very small distances? @lukicdarkoo 

![image](https://user-images.githubusercontent.com/13640533/156567615-03f3e75e-372f-471e-9773-f94342f0c921.png)
![image](https://user-images.githubusercontent.com/13640533/156567684-a46fd856-9f75-4958-a75d-ff47e668bbd1.png)

**Comment by lukicdarkoo** [comment]
> Distance Range | 120 ~ 3,500mm

https://www.robotis.us/360-laser-distance-sensor-lds-01-lidar/

To je oke ponasanje, tako radi i fizicki lidar
