### ISSUE TITLE
Zakunacana vrijednost unutar mep3_bringup/launch/robot_launch.py fajla 

### ISSUE THREAD

**Issue by MarijaGolubovic** [memristor/mep3#109]
![image](https://user-images.githubusercontent.com/93673097/156884024-c0f94f7a-d7f7-4bcd-a8da-8e2f69be365b.png)
Potrebno je unutar fajla mijenjati kada pokrecemo novu strategiju

**Comment by filiparag** [comment]
Ispravljeno u [2c1b81e](https://github.com/memristor/mep3/commit/2c1b81e73a6a51170563075321c26eab206a91e2).
