### ISSUE TITLE
Staviti u launch file opciju da se isključe kamera i protivnički roboti

### ISSUE THREAD

**Issue by VladimirVincan** [memristor/mep3#115]
Predložio bih da za sada, po defaultu i kamera i protivnički roboti budu isključeni kako bi se dodatni fičeri mogli lakše ubacivati i testirati (trenutno moramo ručno da isključimo kontrolere kad nešto novo radimo).

**Comment by lukicdarkoo** [comment]
Implementirano iskljucivanje protivnickih robota u #142
