### ISSUE TITLE
Promeniti svuda naziv `galactic_ws` u `ros2_ws`

### ISSUE THREAD

**Issue by VladimirVincan** [memristor/mep3#135]
Primetio sam za sad na sledećim mestima: 
https://github.com/memristor/mep3/blob/09c6999e7f14d643f0731080cdbf0c958d03c0e2/README.md?plain=1#L25-L29
https://github.com/memristor/mep3/blob/09c6999e7f14d643f0731080cdbf0c958d03c0e2/README.md?plain=1#L76
https://github.com/memristor/mep3/blob/09c6999e7f14d643f0731080cdbf0c958d03c0e2/README.md?plain=1#L101
https://github.com/memristor/mep3/blob/24cb99722f164fb583e46a46f7c9367994dd4063/install.bash#L44-L51

**Comment by lukicdarkoo** [comment]
Msm da je ovo rijeseno
