### ISSUE TITLE
Excavation Squares

### ISSUE THREAD

**Issue by VladimirVincan** [memristor/mep3#21]
![image](https://user-images.githubusercontent.com/13640533/142285555-03148516-3b34-4d22-a8d6-f87f29703998.png)

![image](https://user-images.githubusercontent.com/13640533/142285827-c9c8079a-3403-47d4-af11-5ff6ebf62912.png)

Bacite pogled na excavation squares. Za sad koliko vidim, ostala su 2 problema da se reše: 
1. Kolika je masa tih pločica, odnosno gustina drveta
2. Podesiti da zglob ima odgovarajući opseg. Ako povećam opseg koji može imati zglob, taj opseg kao da nestane kad primenim silu, odnosno pločice ne prestanu da se vrte. Koliko sam shvatio, maksimalni opseg zgloba je Pi. Poželjno bi bilo da kad pločice padnu, stoje vertikalno usled sile gravitacije, umesto pod uglom. I sad u toku simulacije se desi da se pločice vrte koji krug, ali završe u krajnjem dozvoljenom položaju zgloba.

**Comment by lukicdarkoo** [comment]
> Kolika je masa tih pločica, odnosno gustina drveta

Samo nadji okvirno gustinu drveta i bice vise nego dobro :)

> Podesiti da zglob ima odgovarajući opseg. Ako povećam opseg koji može imati zglob, taj opseg kao da nestane kad primenim silu, odnosno pločice ne prestanu da se vrte. Koliko sam shvatio, maksimalni opseg zgloba je Pi. Poželjno bi bilo da kad pločice padnu, stoje vertikalno usled sile gravitacije, umesto pod uglom. I sad u toku simulacije se desi da se pločice vrte koji krug, ali završe u krajnjem dozvoljenom položaju zgloba.

Ako ti PROTO izgleda `Solid (bez fizike) > Solid (sa fizikom) > HingeJoint > Solid (sa fizikom)` plocice bi trebalo da se zaustave kolizijom, ne treba ti min/maxStop. Mislim da ce to ubrzati simulaciju.

Slobodno napravi PR, pa mozemo tamo komentarisati
