### ISSUE TITLE
Code is doubled, does not compile, just delete lines 198... 206 in /home/filip/galactic_ws/src/mep3/mep3_behavior_tree/include/mep3_behavior_tree/team_color_strategy_mirror.hpp

### ISSUE THREAD

**Issue by alfitec** [memristor/mep3#224]
/home/filip/galactic_ws/src/mep3/mep3_behavior_tree/include/mep3_behavior_tree/team_color_strategy_mirror.hpp:207:22: error: ‘static std::string mep3_behavior_tree::StrategyMirror::strip_server_name(const string&)’ cannot be overloaded with ‘static std::string mep3_behavior_tree::StrategyMirror::strip_server_name(const string&)’

**Comment by MarijaGolubovic** [comment]
We fixed the bug, the code should compile without any problems. Thank You for the suggestion.
