### ISSUE TITLE
BehaviorTree - `NavigateToAction` ne može da se halt-uje

### ISSUE THREAD

**Issue by filiparag** [memristor/mep3#35]
Trenutna implementacija `NavigateToAction` akcije ne može da se halt-uje.

Test stablo za verifikaciju rešenja je na slici ispod. Robot treba da se zaustavi nakon 5 sekundi i da se tada ispiše 
`[ERROR] [ <timestamp> ] [behavior_tree_ros_node]: Halted the action`

![Tree](https://user-images.githubusercontent.com/4471044/145732661-238397fe-9dbe-4384-95fb-4a02254243a5.png)

[`TODO` referenca u kodu](https://github.com/memristor/mep3/blob/main/mep3_planning/include/mep3_planning/navigate_to_action.hpp#L80-L81)

**Comment by angstrem98** [comment]
Brišemo ako je rešeno?

**Comment by filiparag** [comment]
Problem se više ne javlja, zatvaram issue.
