### ISSUE TITLE
Adding support for MX28 servo

### ISSUE THREAD

**Issue by miloshunter** [memristor/mep3#72]
- [ ] Handling of the difference in GoalPosition arguments
- [ ] Add handling of errors to know what failure exactly happened
- [ ] Decide what to do if the command is unachievable? (Service call position is out of available range)

Some differences include GoalPosition arguments:
![image](https://user-images.githubusercontent.com/10269630/150956272-010057c9-7047-4768-8816-2fbdc9fe973f.png)

**Comment by miloshunter** [comment]
The [MX28 Dynamixel servo](https://emanual.robotis.com/docs/en/dxl/mx/mx-28/) uses [Protocol 2.0.](https://emanual.robotis.com/docs/en/dxl/protocol2/)

The main difference is in how the packet is formed:
![image](https://user-images.githubusercontent.com/10269630/150956575-5071ba90-1c04-44b7-aa6b-44fcb4eba700.png)


Some differences include GoalPosition arguments:
![image](https://user-images.githubusercontent.com/10269630/150956272-010057c9-7047-4768-8816-2fbdc9fe973f.png)

**Comment by lukicdarkoo** [comment]
Sredjeno u #196
